<?php

namespace tests\resources;

use p4it\rest\client\ActiveResourceQuery;
use p4it\rest\client\BadResponseException;
use yii\base\InvalidConfigException;
use yii\httpclient\Exception;

/**
 * @property $room_slot_id
 * @property $type
 * @property $file_history_id
 * @property $created_at
 * @property $updated_at'
 */

class PhotoRoomSlotHasFileQuery extends ActiveResourceQuery {

    /**
     * @param null $db
     * @return PhotoRoomSlotHasFile|bool
     * @throws InvalidConfigException
     * @throws Exception
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return PhotoRoomSlotHasFile[]
     * @throws BadResponseException
     * @throws InvalidConfigException
     * @throws Exception
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}
